package com.example.b07demosummer2024;

import android.graphics.Color;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentTransaction;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;
import java.util.ArrayList;
import java.util.List;

public class RecyclerViewStaticFragment extends Fragment {
    private RecyclerView recyclerView;
    private Button buttonBack;
    private Button buttonNext;
    private TextView pageNoInfo;
    private ItemAdapter itemAdapter;
    private List<Item> itemList;
    private int pageNumber = 1;
    private int maxPages;

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_recycler_view, container, false);
        itemList = new ArrayList<>();
        loadStaticItems();
//        itemAdapter = new ItemAdapter(itemList.subList(0, Math.min(itemList.size(),10)), getParentFragmentManager());
//        recyclerView.setAdapter(itemAdapter);
        maxPages = itemList.size() / 10 + 1;
        recyclerView = view.findViewById(R.id.recyclerView);
        buttonBack = view.findViewById(R.id.buttonBack);
        buttonNext = view.findViewById(R.id.buttonNext);
        pageNoInfo = view.findViewById(R.id.textView2);
        pageNoInfo.setText(makePageString());
        recyclerView.setLayoutManager(new LinearLayoutManager(getContext()));

        ensureButtonBounds();
        createAdapter();

        buttonBack.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                pageNumber--;
                pageNoInfo.setText(makePageString());
                createAdapter();
                ensureButtonBounds();
            }
        });

        buttonNext.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                pageNumber++;
                pageNoInfo.setText(makePageString());
                createAdapter();
                ensureButtonBounds();
            }
        });

        return view;
    }

    private String makePageString() {
        return "Page " + pageNumber + " of " + maxPages;
    }

    private void ensureButtonBounds() {
        if (pageNumber == 1) {
            buttonBack.setEnabled(false);
            buttonBack.getBackground().setTint(Color.DKGRAY);
        } else {
            buttonBack.setEnabled(true);
            buttonBack.getBackground().setTint(Color.BLACK);
        }
        if (pageNumber == maxPages) {
            buttonNext.setEnabled(false);
            buttonNext.getBackground().setTint(Color.GRAY);
        } else {
            buttonNext.setEnabled(true);
            buttonNext.getBackground().setTint(Color.BLACK);

        }
    }

    private void createAdapter() {
        itemAdapter = new ItemAdapter(itemList.subList(Math.max(0, (pageNumber - 1) * 10), Math.min(itemList.size(), (pageNumber) * 10)), getParentFragmentManager());
//        itemAdapter = new ItemAdapter(itemList, getParentFragmentManager());
        recyclerView.setAdapter(itemAdapter);
    }

    private void loadStaticItems() {
        // Load static items from strings.xml or hardcoded values
        itemList.add(new Item("#1", "A Tang 'Sancai' 'Baoxianghua' Box", "Box", "Tang Dynasty", "This tricolor (sancai) box has a round shape with shallow straight walls, a concave circular mouth, a flat base, and a slightly curved lid. The outer surface of the lid is decorated with intricate molded patterns, displaying exquisite and varied designs. The exterior of the box is covered in tricolor glazes, including green, yellow, white, and blue. The interior of the box and the base are covered in yellow glaze. The entire piece is adorned with fine crackle patterns. During the mid-Tang Dynasty, the tricolor glazing technique reached its peak, resulting in a wide variety of vessel forms and refined craftsmanship. The glaze colors during this period were lustrous and the coloring appeared natural. Vessels were often fully glazed both on the inside and outside, utilizing colors such as green, yellow, white, blue, and black, creating a complex and diverse palette. The production process involved applying a base layer of slip before adding various colored glazes to achieve the desired overall effect in terms of both form and decoration. The decoration techniques included carving, stamping, appliqué, and modeling. These tricolor artifacts showcased rich content and were considered exquisite examples of Tang tricolor ware.", "https://media.discordapp.net/attachments/1254846354245685400/1267987778533064725/Screenshot_2024-07-30_at_7.30.39_PM.png?ex=66aac924&is=66a977a4&hm=351e4a6dc7f370a15cd1de991e6f4574faba4880a53d9a618e70a2dcbf9c283f&=&format=webp&quality=lossless&width=828&height=644"));
        itemList.add(new Item("#2", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#3", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#4", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#5", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#6", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#7", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#8", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#9", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#10", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#11", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#12", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#13", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#14", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#15", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#16", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#17", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#18", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#19", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#20", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#21", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#22", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#23", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#24", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#25", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#26", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#27", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#28", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#29", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#30", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#31", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#32", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#33", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#34", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#35", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#36", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#37", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#38", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#39", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#40", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#41", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#42", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));
        itemList.add(new Item("#43", "A Blue-Glazed Ceramic 'Tiger'", "Tiger", "Three Kingdoms Period", "This blue-glazed ceramic tiger was crafted during the Three Kingdoms Period and originates from the Yue Kiln. It features a rounded and well-proportioned form with a slanting neck and circular mouth. The abdomen showcases a bow-shaped handle resembling a tiger in motion, with the tiger's head tilted upwards at a 45-degree angle and a round open mouth. The lower abdomen is sculpted to depict contracted limbs. The handle behind the tiger's head is also adorned with delicate lines. The entire piece is covered in a light blue glaze. Another similar piece with the same design measures 15.7cm in height, 20.9cm in length, and has a mouth diameter of 4.8cm. This tiger was unearthed in 1955 in Zhao Shigang, Nanjing, Jiangsu Province. In August 2013, it was listed in the \"Third Batch of Cultural Relics Prohibited from Going Abroad (Abroad) for Exhibition\" by the National Cultural Heritage Administration. Inscribed on its lower abdomen are thirteen characters: \"Crafted by Master Yuan Yi from Shangyu, Kuaiji, in the 14th year of Chiwu.\" This piece represents one of the earliest known ceramics with an accurate dating inscription discovered through archaeological excavation.", "https://media.discordapp.net/attachments/1254846354245685400/1268049986285994004/Screenshot_2024-07-30_at_11.37.51_PM.png?ex=66ab0313&is=66a9b193&hm=3397910bf664044c4b9dcc367813f6b68caf78529e1b46d59e210b78cda55f77&=&format=webp&quality=lossless&width=832&height=676"));

    }
}
